apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-webapp-deployment
  labels:
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: webapp
        image: yoursureshdockerhub/kubernetes-fe
        ports:
        - containerPort: 80
        

   
        

