apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-webapp-deployment
  labels:
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: webapp
        image: yoursureshdockerhub/jenkins-eks-fe:latest
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_URL
          value: "http://a92b668ed53e44b02b1d1edc98c56c65-1705079801.eu-central-1.elb.amazonaws.com:8080/api"
        

   
        

