apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-webapp-deployment
  labels:
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: webapp
        image: yoursureshdockerhub/kubernetes-fe:latest
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_URL
          value: "http://abe7443a9971d4a908b9387ed26872a6-1504074029.eu-central-1.elb.amazonaws.com:8080/api"
        

   
        

