apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    tier: frontend   # Match pods with the "tier: frontend" label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort   # Expose service via NodePort in Minikube
